SEMANTIC_ANTICIPATOR:
  type: 'sem_rgbd'
  resnet_type: 'resnet18'
  unet_nsf: 32
  nclasses: 1
  map_scale: 0.02
  map_size: 251
  imgh: 240
  imgw: 320
  maxmium_object_num: 6
  device: 'cuda:1'
  ckpt: 19
  freeze_features: False
  

OUTPUT_NORMALIZATION:
  channel_0: "sigmoid"
  channel_1: "sigmoid"

IMG_NORMALIZATION:
  res18_img_mean: [0.485, 0.456, 0.406]
  res18_img_std: [0.229, 0.224, 0.225]
  focal_img_mean: [123.675, 116.28, 103.53]
  focal_img_std: [58.395, 57.12, 57.375]